lista_asistencias_merino_espinoza/Models/reuniones.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lista_asistencias_merino_espinoza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reuniones
    {
        public int id_reunion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string fecha { get; set; }
    }
}

lista_asistencias_merino_espinoza/Controllers/ReunionesController.cs
using lista_asistencias_merino_espinoza.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace lista_asistencias_merino_espinoza.Controllers
{
    public class ReunionesController : Controller
    {
        lista_asistenciasEntitie db = new lista_asistenciasEntitie();
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult listar()
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<reuniones> lt = db.reuniones.OrderBy(u => u.nombre).ToList<reuniones>();
            return Json(new { data = lt }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult modificar(reuniones ob)
        {
            if (ob.id_reunion > 0)
            {
                reuniones usu = db.reuniones.Where(m => m.id_reunion == ob.id_reunion).FirstOrDefault<reuniones>();
                usu.id_reunion = ob.id_reunion;
                usu.nombre = ob.nombre;
                usu.descripcion = ob.descripcion;
                usu.fecha = ob.fecha;

                db.SaveChanges();
                return Json(new { result = true, message = "Datos editados correctamente!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                reuniones usu = new reuniones();
                usu.nombre = ob.nombre;
                usu.descripcion = ob.descripcion;
                usu.fecha = ob.fecha;

                db.reuniones.Add(ob);
                db.SaveChanges();
                return Json(new { result = true, message = "Datos registrados correctamente!" }, JsonRequestBehavior.AllowGet);
            }

        }

        public JsonResult editar(int id)
        {
            var de = db.reuniones.Where(m => m.id_reunion == id).FirstOrDefault();
            return Json(de, JsonRequestBehavior.AllowGet);
        }

        public JsonResult eliminar(int id)
        {
            reuniones d = db.reuniones.Where(m => m.id_reunion == id).FirstOrDefault<reuniones>();
            db.reuniones.Remove(d);
            db.SaveChanges();

            return Json(new { result = true, message = "Datos eliminados correctamente!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

lista_asistencias_merino_espinoza/Views/Reuniones/Index.cshtml
@model lista_asistencias_merino_espinoza.Models.reuniones
@{
    ViewBag.Title = "Lista de reuniones";
}
<br />
<button class="btn btn-success" onclick="agregar()">Agregar Reunion</button>
<hr />
<div class="table-responsive">
    <table id="tabla" class="table table-hover table-bordered" style="width: 100%">
        <thead class="bg-secondary text-white">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nombre</th>
                <th scope="col">Descripcion</th>
                <th scope="col">fecha</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>


@*Creando modal para agregar*@
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="tituloModal"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("modificar", "Reuniones", FormMethod.Post, new { @id = "formDatos" }))
                {
                    @Html.HiddenFor(m => m.id_reunion, new { @id = "id" })
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        @Html.TextBoxFor(m => m.nombre, new { @class = "form-control", @name = "nombre", @placeholder = "Nombre de la reunion" })
                    </div>
                    <div class="form-group">
                        <label for="descripcion">Descripcion</label>
                        @Html.TextAreaFor(m => m.descripcion, new { @class = "form-control", @name = "descripcion", @placeholder = "Descripcion de la reunion", @rows = "6" })
                    </div>
                    <div class="form-group">
                        <label for="fecha">Fecha</label>
                        @Html.TextBoxFor(m => m.fecha, new { @class = "form-control", @name = "fecha", @placeholder = "Fecha de la reunion", @type = "date" })
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" id="btnRegistrar" class="btn btn-primary" onclick="btnRegistrar()">Registrar</button>
                <button type="button" id="btnEditar" class="btn btn-primary" onclick="btnEditar()">Guardar Cambios</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/notify.min.js"></script>

    <script>
        var Datatables;

        Datatables = $('#tabla').DataTable({
                "ajax": {
                    "type": "GET",
                    "url": '@Url.Action("listar", "Reuniones")',
                    "datatype": "JSON"
                },
                "columns": [
                    { "data": "id_reunion" },
                    { "data": "nombre" },
                    { "data": "descripcion" },
                    { "data": "fecha" },
                    {
                        "data": "id_reunion", "render": function (data) {
                            html = "<button onclick='editar(" + data + ")' type='button' class='btn btn-primary btn-sm'>Editar</button>";
                            html += "<button onclick='eliminar(" + data + ")' type='button' class='btn btn-danger btn-sm'>Eliminar</button>";
                            return html;
                        }
                    },
                ]
            });


        function agregar() {
            $("#id").val("");
            $("#nombre").val("");
            $("#descripcion").val("");
            $("#fecha").val("");

            $('#btnRegistrar').show();
            $('#btnEditar').hide();

            $("#tituloModal").html("Registrar");

            $('#modal').modal();
        }

        function btnRegistrar() {
            if ($("#nombre").val() != "" && $("#fecha").val() != "") {
                var datos = $("#formDatos").serialize();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("modificar", "Reuniones")',
                    data: datos,
                    success: function (respuesta) {
                        if (respuesta.result) {
                            $('#modal').modal("hide");
                            Datatables.ajax.reload();
                            $.notify(respuesta.message, {
                                globalPosition: 'top right',
                                className: 'success'
                            });
                        }
                    },
                    error: function (msg) {
                        alert(msg.responsetext);
                    }
                });
            } else {
                $.notify("Nombre y/o fecha no pueden estar vacios!", {
                    globalPosition: 'top right',
                    className: 'error'
                });
            }
        }

        function btnEditar() {
            
            if ($("#id").val() != "" && $("#nombre").val() != "" && $("#fecha").val() != "") {
                var datos = $("#formDatos").serialize();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("modificar", "Reuniones")',
                    data: datos,
                    success: function (respuesta) {
                        if (respuesta.result) {
                            $('#modal').modal("hide");
                            Datatables.ajax.reload();
                            $.notify(respuesta.message, {
                                globalPosition: 'top right',
                                className: 'success'
                            });
                        }
                    },
                    error: function (msg) {
                        alert(msg.responsetext);
                    }
                });
            }
        }

        function eliminar(id) {
            if (confirm("Seguro que desea eliminar el registro?")) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("eliminar", "Reuniones")' + id,
                    datatype: "JSON",
                    success: function (respuesta) {
                        if (respuesta.result) {
                            Datatables.ajax.reload();
                            $.notify("Datos eliminados!", {
                                globalPosition: 'top right',
                                className: 'success',
                            });
                        }
                    },
                    error: function (msg) {
                        alert(msg.responsetext);
                    }
                });
            }
        }

        function editar(id) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("editar", "Reuniones")' + id,
                datatype: 'JSON',
                success: function (respuesta) {
                    $("#id").val(respuesta.id_reunion);
                    $("#nombre").val(respuesta.nombre);
                    $("#descripcion").val(respuesta.descripcion);
                    $("#fecha").val(respuesta.fecha);
                    $('#modal').modal();

                    $("#tituloModal").html("Editar");

                    $('#btnRegistrar').hide();
                    $('#btnEditar').show();
                },
                error: function (msg) {
                    alert(msg.responsetext);
                }
            });
        }
    </script>
}